logging:
    file:
        path: ${LOG_FOLDER:logs}
    level:
        root: ${LOG_LEVEL:INFO}

spring:
    application:
        name: lms
    security:
        user:
            name: ${SECURITY_USERNAME}
            password: ${SECURITY_PASSWORD}
    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
                connection:
                    characterEncoding: UTF-8
                    charset: UTF-8
                    useUnicode: true
                format_sql: true

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    #        show-sql: true
    jackson:
        date-format: yyyy-MM-dd
minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket-name: ${MINIO_BUCKET_NAME}

app:
    department: ${DEPARTMENT}
    export-folder: ${EXPORT_FOLDER}

ini:
    file-path: ${APP_INI}

